export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const INCREMENT_ITEM_QTY = 'INCREMENT_ITEM_QTY';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const DECREMENT_ITEM_QTY = 'DECREMENT_ITEM_QTY';
export const CLEAR_CART = 'CLEAR_CART';