export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST';
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS';
export const ITEM_LIST_FAIL = 'ITEM_LIST_FAIL';

export const ITEMS_BY_CATEGORY_REQUEST = 'ITEMS_BY_CATEGORY_REQUEST';
export const ITEMS_BY_CATEGORY_SUCCESS = 'ITEMS_BY_CATEGORY_SUCCESS';
export const ITEMS_BY_CATEGORY_FAIL = 'ITEMS_BY_CATEGORY_FAIL';